types/collection/types.ts, types/index.d.ts, types/item/types.ts, types/search/types.ts, types/user/types.ts
* Add collection type
* Rename detail to item
* Add type for: keyof Filter
=> feat: add-collection-type

types/collection/types.ts, types/core/content.ts, types/index.d.ts, types/item/types.ts, types/search/types.ts
This PR is part of a triplet:
* https://github.com/viaacode/avo2-client/pull/31
* https://github.com/viaacode/avo2-proxy/pull/12
They need to be merged at the same time
=> feat: use graphql db for retrieving item and collection detail info

types/collection/types.ts
new format for collections after they are converted to the avo2 system
=> feat: collection fragment new format

types/collection/types.ts
=> feat(collection): add note field and item_meta field to collection type

types/content/types.ts, types/index.d.ts, types/menu/types.ts
Fixes: https://github.com/viaacode/avo2-client/pull/237#discussion_r350209846
=> feat: add menu and content schemas

types/event-logging/types.ts, types/index.d.ts
some smaller changes to event logging:
https://viaadocumentation.atlassian.net/wiki/spaces/COMP/pages/1019019307/Event+logging
=> feat(logging): update event logging types

types/user/types.ts
These changes are required to support the profile page in the client
=> feat(profile): add education level, subjects and other props to profile

types/assignment/index.ts, types/collection/index.ts, types/index.d.ts
collection_fragment.type is missing, i will take this up with bart
=> fix(collection): update collection types to match db changes

package.json, types/index.d.ts, types/search/index.ts
part of: https://district01.atlassian.net/browse/AVO2-644
This PR requires changes in all 4 repos:
* https://github.com/viaacode/avo2-typings/pull/56
* https://github.com/viaacode/avo2-components/pull/267
* https://github.com/viaacode/avo2-proxy/pull/112
* https://github.com/viaacode/avo2-client/pull/496
=> fix(search): update search types, add lint npm command + fix errors

package-lock.json, package.json, types/index.d.ts, types/interactive-tour/index.ts
Needed, because we need to show interactive tours on content pages
content pages can be loaded without the user being logged in, so we cannot get the interactive tours straight from the database, so we need to get the tours through the proxy, so both the client and the proxy need access to these types
=> Feature: Interactive Tour types

types/file-upload/index.ts, types/index.d.ts
In client stond hier een comment van @bertyhell  om dit in typings te gooien, dus heb dit ook even gedaan.
=> feat(file-upload): add ZendeskFileInfo

types/content/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-566
=> Fix: add thumnail_path to Avo.Content.Content

types/user/index.ts
part of: https://meemoo.atlassian.net/browse/DEV-781
=> fix(user): remove id, has been superseded by uid property

types/collection/index.ts, types/content/index.ts, types/user/index.ts
relates to: https://meemoo.atlassian.net/browse/DEV-781
=> fix(user): remove database fields that were removed from types

types/assignment/index.ts, types/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-569
=> fix(assignment-labels): update assignment labels

types/item/index.ts
relates to: https://meemoo.atlassian.net/browse/AVO-284
=> feat(item): add note field

types/collection/index.ts
part of: 
* https://meemoo.atlassian.net/browse/AVO-291
* https://meemoo.atlassian.net/browse/AVO-302
=> feat(collection): add update_by_profile props to collection interface

types/collection/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-552
=> feat(collection): add relations property

types/auth/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-477
=> feat(auth): add session expire date to check login response type

types/content/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-804
=> fix(content-page): fix wrong label array type

types/content/index.ts
closes: https://meemoo.atlassian.net/browse/AVO-805
=> feat(content-page): add seo_description prop to avo.content.content

types/newsletter/index.d.ts, types/user/index.d.ts
part of: 
* https://meemoo.atlassian.net/browse/AVO-922
* https://meemoo.atlassian.net/browse/AVO-838
=> feat(profile): add company props and newletter all users prop

types/user/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-870
=> Add organisation property to profile interface

types/user/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-926
=> feat(user): add is_exception and title (oormerk) to profile interface

types/collection/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-505
=> Feat: add briefing id to collection interface

types/event-logging/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-1221
=> fix(logging): update logging format

types/search/index.d.ts
Necessary for https://meemoo.atlassian.net/browse/AVO-479.
=> feat(search): search option request

types/collection/index.d.ts, types/content-page/index.d.ts, types/core/index.d.ts, types/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-1091
=> feat(content-page): add link_to prop to content page labels

types/index.d.ts, types/item/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-468
=> feat(item): add subtitle property to item interface

types/item/index.d.ts
part of https://meemoo.atlassian.net/browse/AVO-278
=> feat(items): add count property to the item interface

types/user/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-1385
=> feat(user): add full_name to user interface

types/collection/index.d.ts, types/index.d.ts
part of: https://meemoo.atlassian.net/browse/AVO-1305
=> feat(collection): add management types

types/event-logging/index.d.ts, types/user/index.d.ts
Added `temp_access` property in `User` with type `UserTempAccess`.
=> feat(user): add temp access object

types/event-logging/index.d.ts
=> feat: update event logging type

types/assignment/index.d.ts, types/index.d.ts
=> feat(avo-1916): add initial typings for assignment v2

package-lock.json, package.json, types/assignment/index.d.ts
**Jira**
In het algemeen nodig (voor cleanup) maar ook voor komende tickets waaronder 2568
=> feat(avo-2568): provide typings for assignments v2

types/index.d.ts, types/lom/index.d.ts
[AVO-2639](https://meemoo.atlassian.net/browse/AVO-2639)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1763)
[AVO-2639]: https://meemoo.atlassian.net/browse/AVO-2639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(avo-2639): adjust lom schema

types/collection/index.d.ts
[AVO-2613](https://meemoo.atlassian.net/browse/AVO-2613)
[AVO-2643](https://meemoo.atlassian.net/browse/AVO-2643)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1785)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/641)
[AVO-2613]: https://meemoo.atlassian.net/browse/AVO-2613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2643]: https://meemoo.atlassian.net/browse/AVO-2643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(avo-2613): Add profile to contributors schema on collections

types/assignment/index.d.ts
[AVO-2630](https://meemoo.atlassian.net/browse/AVO-2630)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1788)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/644)
[AVO-2630]: https://meemoo.atlassian.net/browse/AVO-2630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(avo-2630): Add thumbnail path to assignment schema

types/edit-status/index.d.ts, types/index.d.ts
[AVO-2650](https://meemoo.atlassian.net/browse/AVO-2650)
[AVO-2651](https://meemoo.atlassian.net/browse/AVO-2651)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/649)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1792)
[AVO-2650]: https://meemoo.atlassian.net/browse/AVO-2650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2651]: https://meemoo.atlassian.net/browse/AVO-2651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(avo-2650): add edit status response schema and edit status info schema

types/search/index.d.ts
[AVO-2670](https://meemoo.atlassian.net/browse/AVO-2670)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1802)
[AVO-2670]: https://meemoo.atlassian.net/browse/AVO-2670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(avo-2670): add owner to search result

types/assignment/index.d.ts
[AVO-2627](https://meemoo.atlassian.net/browse/AVO-2627)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1804)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/653)
[AVO-2627]: https://meemoo.atlassian.net/browse/AVO-2627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(avo-2627): Add note to assignment schema

types/collection/index.d.ts, types/lom/enums.d.ts, types/lom/enums.ts, types/lom/index.d.ts, types/search/index.d.ts, types/user/index.d.ts
https://meemoo.atlassian.net/browse/AVO-2755
=> feat(avo-2755): switch to loms
